version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    depends_on:
      - db

  scheduler:
    build: .
    command: python scheduler_main.py
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
